import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Playfair_Display_SC } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400","500","600","700","800","900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${playfairDisplay.className} antialiased overflow-x-hidden w-full`}
      >
        <Navbar />
        <div className="pt-16 w-full overflow-x-hidden">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
